# Generated by Django 3.2.3 on 2021-06-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contactinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinformation',
            name='name',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
