# Generated by Django 3.2.3 on 2021-06-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_cart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discounted_price',
            field=models.IntegerField(default=0),
        ),
    ]
