# Generated by Django 3.2.3 on 2021-06-08 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
