# Generated by Django 3.2.3 on 2021-06-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210608_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
    ]
