# Generated by Django 3.2.3 on 2021-06-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20210615_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='addtotal',
            field=models.IntegerField(null=True),
        ),
    ]
