# Generated by Django 3.2.3 on 2021-06-17 11:34

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_cart_addtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='addtotal',
            field=models.PositiveIntegerField(verbose_name=home.models.Cart.addtotal),
        ),
    ]
